add some libraries, PHP extensions and frameworks.
pmjones/php-history pull request #29
Opened 2016-10-13 21:51 UTC by peter279k

Hi @pmjones , I add some frameworks and libraries. For example, Guzzle , Nette and Silex.

2016-10-14 01:18 UTC, sergeyklay commented
@peter279k Could you please rebase

2016-10-14 05:06 UTC, peter279k commented
Hi @sergeyklay , I rebase it now :).

2016-10-18 19:49 UTC, pmjones commented
Hey @peter279k -- Some of the entries you list are not frameworks. If you can remove the non-framework ones (e.g. pecl, apc, memcache, and guzzle) I will review again and merge.

2016-10-18 20:15 UTC, sergeyklay requested changes

2016-10-18 20:15 UTC, sergeyklay commented on README.md
> +- Phalcon 2: <https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md>
Wrong, 2015

2016-10-18 20:15 UTC, sergeyklay commented on README.md
> +- Phalcon 3: <https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md>
Duplicate

2016-10-18 20:15 UTC, sergeyklay commented on README.md
> +- Phalcon 1: <https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md>
Duplicate + wrong

2016-10-18 20:15 UTC, sergeyklay commented on README.md
> +- Phalcon 1: <https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md>
Duplicate + wrong

2016-10-19 06:02 UTC, peter279k commented
Thanks for the review. I remove the duplicated entries and remove the non framework entries.

2016-10-19 20:37 UTC, pmjones commented
Sorry, last change -- PEAR 1 is a "library collection" so it stays. That's the only issue left; once it gets added back I can merge. Thanks again!

2016-10-30 03:25 UTC, merged